on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20.x
      - name: Pkg
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: userscript
          path: dist/main.user.js

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: userscript
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "main.user.js"